name: Create CloudFront Invalidation

env:
  NODE_VERSION: '20.12.1'

run-name: Create CloudFront Invalidation (${{ github.event.inputs.team }}/${{ github.event.inputs.project }}/${{ github.event.inputs.environment }}/${{ github.event.inputs.git_ref || github.ref_name }})
on:
  workflow_dispatch:
    inputs:
      git_ref:
        description: 'Branch to invalidate CloudFront cache for (leave blank to use the branch dropdown above)'
        required: false
      team:
        type: choice
        description: Team
        required: true
        options:
          - sheer-energy
          - dotcom
          - aura
          - unified-wp
          - reporting
          - trash-titans
      environment:
        type: choice
        description: Run in this Environment
        required: true
        default: nonprod
        options:
          - prod
          - nonprod
      project:
        type: choice
        description: Project
        options:
          - ries-hub-ui
          - rs-frontend
          - rs-header
          - rs-footer
          - rs-search
          - rs-sustainability
          - rs-shop
          - aura
          - unified-wp
          - reporting
          - rsw-account-ui

jobs:
  environment:
    runs-on: ubuntu-latest

    steps:
      - name: Inputs Received
        run: |
          echo '### Base branch' >> $GITHUB_STEP_SUMMARY
          echo "${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_STEP_SUMMARY
          echo '### Inputs' >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY
          echo '${{ toJSON(inputs) }}' >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY

  validation:
    runs-on: ubuntu-latest
    name: Validate Workflow
    steps:
      - name: Checkout verify actor action
        uses: actions/checkout@v4
        with:
          repository: RepublicServicesRepository/gha-verify-actor
          ref: refs/heads/main
          token: ${{ secrets.REPUBLIC_SYSTEM_PAT }}
          persist-credentials: false
          fetch-depth: 1
          path: ./.github/actions/verify-actor

      - name: Verify Actor (Sheer Energy)
        uses: ./.github/actions/verify-actor
        if: ${{ github.event.inputs.team == 'sheer-energy' && github.event.inputs.environment == 'prod' }}
        with:
          github_token: ${{ secrets.REPUBLIC_SYSTEM_PAT }}
          whitelist: tstackhouse,pathrph,abiggers

      - name: Verify Actor (RScom)
        uses: ./.github/actions/verify-actor
        if: ${{ github.event.inputs.team == 'dotcom' && github.event.inputs.environment == 'prod' }}
        with:
          github_token: ${{ secrets.REPUBLIC_SYSTEM_PAT }}
          whitelist: tstackhouse,abiggers,jashachik,akaustav,dale-vanzile,desaibr,nikhilramoju,austinrbrown01,WebeWizard,acgilardi,lamasa1,beffjarker,porterlyman,autumnxt

      - name: Verify Actor (AURA)
        uses: ./.github/actions/verify-actor
        if: ${{ github.event.inputs.team == 'aura' && github.event.inputs.environment == 'prod' }}
        with:
          github_token: ${{ secrets.REPUBLIC_SYSTEM_PAT }}
          whitelist: tstackhouse,pathrph,nickdemarco89

      - name: Verify Actor (Unified WP)
        uses: ./.github/actions/verify-actor
        if: ${{ github.event.inputs.team == 'unified-wp' && github.event.inputs.environment == 'prod' }}
        with:
          github_token: ${{ secrets.REPUBLIC_SYSTEM_PAT }}
          whitelist: tstackhouse,pathrph,nickdemarco89

      - name: Verify Actor (Reporting)
        uses: ./.github/actions/verify-actor
        if: ${{ github.event.inputs.team == 'reporting' && github.event.inputs.environment == 'prod' }}
        with:
          github_token: ${{ secrets.REPUBLIC_SYSTEM_PAT }}
          whitelist: tstackhouse,pathrph,nickdemarco89

  clear-cloudfront:
    name: Create CloudFront Invalidation
    permissions:
      id-token: write
      contents: read

    runs-on: ubuntu-latest
    needs: [validation]

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          filter: tree:0

      - name: üõ†Ô∏è Setup Node.js and Install Dependencies
        uses: ./.github/actions/setup-node-install
        with:
          node-version: ${{ env.NODE_VERSION }}

      # TBD
      # - name: Configure AWS credentials (RIES Hub Nonprod)
      #   uses: aws-actions/configure-aws-credentials@v4
      #   if: ${{ github.event.inputs.team == 'sheer-energy' && github.event.inputs.environment == 'nonprod' }}
      #   with:
      #     role-to-assume: ${{ vars.RIES_HUB_OIDC_SSO_DEV_ROLE }}
      #     role-session-name: 'github_actions-ries_hub_sso-dev'
      #     aws-region: us-west-2

      # TBD
      # - name: Configure AWS credentials (RIES Hub Prod)
      #   uses: aws-actions/configure-aws-credentials@v4
      #   if: ${{ github.event.inputs.team == 'sheer-energy' && github.event.inputs.environment == 'prod' }}
      #   with:
      #     role-to-assume: ${{ vars.RIES_HUB_OIDC_SSO_PROD_ROLE }}
      #     role-session-name: 'github_actions-ries_hub_sso-prod'
      #     aws-region: us-west-2

      - name: Configure AWS credentials (RScom Nonprod & RSW Account Nonprod)
        uses: aws-actions/configure-aws-credentials@v4
        if: ${{ (github.event.inputs.team == 'dotcom' || github.event.inputs.team == 'trash-titans') && github.event.inputs.environment == 'nonprod' }}
        with:
          role-to-assume: ${{ vars.RSCOM_OIDC_SSO_DEV_ROLE }}
          role-session-name: 'github_actions-rscom_sso-dev'
          aws-region: us-west-2

      - name: Configure AWS credentials (RScom Prod & RSW Account Prod)
        uses: aws-actions/configure-aws-credentials@v4
        if: ${{ (github.event.inputs.team == 'dotcom' || github.event.inputs.team == 'trash-titans') && github.event.inputs.environment == 'prod' }}
        with:
          role-to-assume: ${{ vars.RSCOM_OIDC_SSO_PROD_ROLE }}
          role-session-name: 'github_actions-rscom_sso-prod'
          aws-region: us-west-2

      - name: Configure AWS credentials (AURA Nonprod & Unified-WP Nonprod & Reporting Nonprod)
        uses: aws-actions/configure-aws-credentials@v4
        if: ${{ (github.event.inputs.team == 'aura' || github.event.inputs.team == 'unified-wp' || github.event.inputs.team == 'reporting') && github.event.inputs.environment == 'nonprod' }}
        with:
          role-to-assume: ${{ vars.AURA_OIDC_SSO_DEV_ROLE }}
          role-session-name: 'github_actions-aura_sso-dev'
          aws-region: us-west-2

      - name: Configure AWS credentials (Aura Prod & Unified-WP Prod & Reporting Prod)
        uses: aws-actions/configure-aws-credentials@v4
        if: ${{ (github.event.inputs.team == 'aura' || github.event.inputs.team == 'unified-wp' || github.event.inputs.team == 'reporting') && github.event.inputs.environment == 'prod' }}
        with:
          role-to-assume: ${{ vars.AURA_OIDC_SSO_PROD_ROLE }}
          role-session-name: 'github_actions-aura_sso-prod'
          aws-region: us-west-2

      # Fallback if no credentials are set from above
      - name: Configure AWS credentials (Access Key Nonprod)
        uses: aws-actions/configure-aws-credentials@v4
        if: ${{ ! env.AWS_ACCESS_KEY_ID && github.event.inputs.environment == 'nonprod' }}
        with:
          aws-access-key-id: ${{ secrets.AWS_NONPROD_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_NONPROD_SECRET_ACCESS_KEY }}
          aws-region: us-west-2

      # Fallback if no credentials are set from above
      - name: Configure AWS credentials (Access Key Prod)
        uses: aws-actions/configure-aws-credentials@v4
        if: ${{ ! env.AWS_ACCESS_KEY_ID && github.event.inputs.environment == 'prod' }}
        with:
          aws-access-key-id: ${{ secrets.AWS_PROD_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_PROD_SECRET_ACCESS_KEY }}
          aws-region: us-west-2

      - name: Create Invalidation
        env:
          BRANCH: ${{ github.event.inputs.git_ref || github.ref_name }}
          PROJECT: ${{ github.event.inputs.project }}
          ENVIRONMENT: ${{ github.event.inputs.environment }}
        run: |
          node scripts/create-cf-invalidations.js --branch $BRANCH --project $PROJECT --environment $ENVIRONMENT
