name: DHS3 Deploy KM DHS PROD

on:
  workflow_dispatch:
    inputs:
      git_ref:
        description: 'The git reference to deploy (typically a branch or sha)'
        required: true
        default: 'release-km-X.X.X'
      version:
        description: 'The semantic version of the tag to create'
        required: true
        default: 'vX.X.X'

jobs:
  environment:
    runs-on: ubuntu-latest

    steps:
      - name: Inputs Received
        run: |
          echo '### Base branch' >> $GITHUB_STEP_SUMMARY
          echo "${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_STEP_SUMMARY
          echo '### Inputs' >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY
          echo '${{ toJSON(inputs) }}' >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY

  deploy-km-dhs3-prod:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_PROD_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_PROD_SECRET_ACCESS_KEY }}
          aws-region: us-west-2

      - name: Invoke codebuild
        uses: aws-actions/aws-codebuild-run-build@v1.0.16
        with:
          project-name: digital-platform-monorepo-prod-codebuild
          buildspec-override: apps/km-marklogic-dhs/buildspec-dhs3.yml
          env-vars-for-codebuild: |
            DHS3_USERNAME,
            DHS3_PASSWORD,
            DHS3_ENVIRONMENT
        env:
          DHS3_USERNAME: ${{ secrets.KM_PROD_DHS3_USERNAME }}
          DHS3_PASSWORD: ${{ secrets.KM_PROD_DHS3_PASSWORD }}
          DHS3_ENVIRONMENT: prod

      - name: Create KM Release
        uses: comnoco/create-release-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          commitish: ${{ github.event.inputs.git_ref }}
          tag_name: km-dhs/${{ github.event.inputs.version }}
          release_name: km-dhs/${{ github.event.inputs.version }}
