name: Deploy Hub App RC

env:
  NODE_VERSION: '20.12.1'

on:
  push:
    branches:
      - release-hub-*

jobs:
  deploy-release-candidate:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: ðŸ› ï¸ Setup Node.js and Install Dependencies
        uses: ./.github/actions/setup-node-install
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Format branch name
        id: git-branch
        run: |
          BRANCH_NAME=$( \
            ./bin/format-branch-name.sh \
            --branch-name="${{ github.ref }}" \
            --field-separator=/
          )
          echo "name=${BRANCH_NAME}" >> $GITHUB_OUTPUT

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_NONPROD_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_NONPROD_SECRET_ACCESS_KEY }}
          aws-region: us-west-2

      - name: Deploy Infrastructure & Code
        env:
          ENVIRONMENT: uat
          NODE_OPTIONS: '--max_old_space_size=7168'
        run: |
          npx nx run-many \
            --target=deploy \
            --projects='ries-hub-data' \
            --stage=${{ steps.git-branch.outputs.name }} \
            --configuration=uat
          npx nx run-many \
            --target=deploy \
            --projects='ries-hub-api' \
            --stage=${{ steps.git-branch.outputs.name }} \
            --configuration=uat
          npx nx run-many \
            --target=deploy \
            --projects='ries-hub-ui' \
            --stage=${{ steps.git-branch.outputs.name }} \
            --configuration=uat

          npx nx run ries-hub-data:seedpreview --tableName="ries-hub-data-${{ steps.git-branch.outputs.name  }}"
