name: Deploy RS Frontend Prod

on:
  workflow_dispatch:
    inputs:
      git_ref:
        description: 'The git reference to deploy (typically a branch or sha)'
        required: true
        default: 'release-rs-X.X.X'
      version:
        description: 'The semantic version of the tag to create'
        required: true
        default: 'vX.X.X'
      environment:
        description: 'This is prod deployment job for RS Frontend'
        required: true
        default: 'please type prod to deploy to prod environment'

env:
  NODE_VERSION: '20.19.0'
  ENVIRONMENT: ${{ github.event.inputs.environment }}
  NODE_OPTIONS: '--max_old_space_size=7168'
  REMOTE_BASE_URL: '.rscom-prod.awsext.repsrv.com'
  AURA_UI_BASE_URL: '.aura-prod.awsext.repsrv.com'
  UNIFIED_WP_UI_BASE_URL: '.aura-prod.awsext.repsrv.com'
  REPORTING_UI_BASE_URL: '.aura-prod.awsext.repsrv.com'
  RSW_UI_BASE_URL: '.rscom-prod.awsext.repsrv.com'
  AURA_ENABLED: true
  WASTE_PROFILE_ENABLED: true
  REPORTING_ENABLED: true
  RSW_ACCOUNT_ENABLED: true
  SM_UI_BASE_URL: '.rscom-prod.awsext.repsrv.com'
  SM_UI_ENABLED: false

jobs:
  environment:
    runs-on: ubuntu-latest

    steps:
      - name: Inputs Received
        run: |
          echo '### Base branch' >> $GITHUB_STEP_SUMMARY
          echo "${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_STEP_SUMMARY
          echo '### Inputs' >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY
          echo '${{ toJSON(inputs) }}' >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY

  setup:
    name: Setup
    runs-on: ubuntu-latest
    outputs:
      projects: ${{ steps.projects.outputs.projects }}

    steps:
      - uses: actions/checkout@v4

      - name: üõ†Ô∏è Setup Node.js and Install Dependencies
        uses: ./.github/actions/setup-node-install
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Get Apps
        id: projects
        run: |
          PROJECTS=($(bin/get-apps.js -l dotcom geolocation circularity bulk-waste));
          PROJECTS_JSON=$(jq --compact-output --null-input '$ARGS.positional' --args -- "${PROJECTS[@]}" | jq -c -M '{"project": . }');
          echo "projects=${PROJECTS_JSON}" >> $GITHUB_OUTPUT
          echo ""
          echo "Projects to deploy:"
          echo ${PROJECTS[@]}

  deploy-rs-frontend-prod:
    needs: setup
    if: github.event.inputs.environment == 'prod'
    permissions:
      id-token: write
      contents: write

    runs-on: ubuntu-latest
    strategy:
      matrix: ${{ fromJson(needs.setup.outputs.projects) }}

    steps:
      - name: ‚úîÔ∏è Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.git_ref }}

      - name: üõ†Ô∏è Setup Node.js and Install Dependencies
        uses: ./.github/actions/setup-node-install
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: üîë Configure AWS credentials (RScom)
        uses: aws-actions/configure-aws-credentials@v4
        if: startsWith(matrix.project, 'rs-')
        with:
          role-to-assume: ${{ vars.RSCOM_OIDC_SSO_PROD_ROLE }}
          role-session-name: 'github_actions-rscom_sso-prod'
          aws-region: us-west-2

      - name: üõ£Ô∏è Create Infrastructure
        run: |
          npx nx deploy ${{ matrix.project }} --stage=prod --configuration=production

      # Should this tagging happen before we do the build & deploy?
      - name: ‚úÖ Create Release
        uses: comnoco/create-release-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          commitish: ${{ github.event.inputs.git_ref }}
          tag_name: ${{ matrix.project }}/${{ github.event.inputs.version }}
          release_name: ${{ matrix.project }}/${{ github.event.inputs.version }}
