name: DHS3 Deploy KM DHS STG

on:
  push:
    branches:
      - release-km-*

jobs:
  deploy-km-dhs3-stg:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_NONPROD_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_NONPROD_SECRET_ACCESS_KEY }}
          aws-region: us-west-2

      - name: Invoke codebuild
        uses: aws-actions/aws-codebuild-run-build@v1.0.16
        with:
          project-name: digital-platform-ries-hub-dhs-nonprod-codebuild
          buildspec-override: apps/km-marklogic-dhs/buildspec-dhs3.yml
          env-vars-for-codebuild: |
            DHS3_USERNAME,
            DHS3_PASSWORD,
            DHS3_ENVIRONMENT
        env:
          DHS3_USERNAME: ${{ secrets.KM_STG_DHS3_USERNAME }}
          DHS3_PASSWORD: ${{ secrets.KM_STG_DHS3_PASSWORD }}
          DHS3_ENVIRONMENT: stg
