name: Deploy Hub Apps Prod

env:
  NODE_VERSION: '20.19.0'

on:
  workflow_dispatch:
    inputs:
      git_ref:
        description: 'The git reference to deploy (typically a branch or sha)'
        required: true
        default: 'release-hub-X.X.X'
      version:
        description: 'The semantic version of the tag to create'
        required: true
        default: 'vX.X.X'

jobs:
  environment:
    runs-on: ubuntu-latest

    steps:
      - name: Inputs Received
        run: |
          echo '### Base branch' >> $GITHUB_STEP_SUMMARY
          echo "${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_STEP_SUMMARY
          echo '### Inputs' >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY
          echo '${{ toJSON(inputs) }}' >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY

  deploy-pr:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.git_ref }}

      - name: üõ†Ô∏è Setup Node.js and Install Dependencies
        uses: ./.github/actions/setup-node-install
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_PROD_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_PROD_SECRET_ACCESS_KEY }}
          aws-region: us-west-2

      - name: Deploy Infrastructure & Code
        env:
          ENVIRONMENT: prod
          NODE_OPTIONS: '--max_old_space_size=7168'
        run: |
          npx nx run-many \
            --target=deploy \
            --projects='ries-hub-data' \
            --stage=prod \
            --configuration=production
          npx nx run-many \
            --target=deploy \
            --projects='ries-hub-api' \
            --stage=prod \
            --configuration=production
          npx nx run-many \
            --target=deploy \
            --projects='ries-hub-ui' \
            --stage=prod \
            --configuration=production

      - name: Create Hub UI Release
        uses: comnoco/create-release-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          commitish: ${{ github.event.inputs.git_ref }}
          tag_name: ries-hub-ui/${{ github.event.inputs.version }}
          release_name: ries-hub-ui/${{ github.event.inputs.version }}

      - name: Create Hub API Release
        uses: comnoco/create-release-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          commitish: ${{ github.event.inputs.git_ref }}
          tag_name: ries-hub-api/${{ github.event.inputs.version }}
          release_name: ries-hub-api/${{ github.event.inputs.version }}
