name: Deploy Hub DHS QA

on:
  push:
    branches:
      - master
    paths:
      - 'apps/ries-hub-marklogic-dhs/**'

jobs:
  deploy-hub-dhs-qa:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_NONPROD_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_NONPROD_SECRET_ACCESS_KEY }}
          aws-region: us-west-2

      - name: Invoke codebuild
        uses: aws-actions/aws-codebuild-run-build@v1.0.16
        with:
          project-name: digital-platform-ries-hub-dhs-nonprod-codebuild
          buildspec-override: apps/ries-hub-marklogic-dhs/buildspec.yml
          env-vars-for-codebuild: |
            DHS_USERNAME,
            DHS_PASSWORD,
            DHS_ENVIRONMENT
        env:
          DHS_USERNAME: ${{ secrets.RIES_HUB_QA_DHS_USERNAME }}
          DHS_PASSWORD: ${{ secrets.RIES_HUB_QA_DHS_PASSWORD }}
          DHS_ENVIRONMENT: qa
