name: Pull Docker Images and Push to ECR

on:
  workflow_dispatch:
    inputs:
      redis_version:
        description: 'The Docker image version tag for redis'
        required: true
        default: '6.2.6-alpine'
      dynamodb_version:
        description: 'The Docker image version tag for amazon/dynamodb-local'
        required: true
        default: 'latest'
      elasticmq_version:
        description: 'The Docker image version tag for softwaremill/elasticmq'
        required: true
        default: 'latest'
      node_version:
        description: 'The Docker image version tag for node'
        required: true
        default: '18'
env:
  AWS_ACCOUNT_ID: '938423115328'
  AWS_REGION: 'us-west-2'

jobs:
  environment:
    runs-on: ubuntu-latest

    steps:
      - name: Inputs Received
        run: |
          echo '### Base branch' >> $GITHUB_STEP_SUMMARY
          echo "${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_STEP_SUMMARY
          echo '### Inputs' >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY
          echo '${{ toJSON(inputs) }}' >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY

  pull_and_push:
    permissions:
      id-token: write
      contents: read
    runs-on: ubuntu-latest
    strategy:
      matrix:
        images:
          [
            { name: 'redis', tag_input: 'redis_version' },
            { name: 'amazon/dynamodb-local', tag_input: 'dynamodb_version' },
            { name: 'softwaremill/elasticmq', tag_input: 'elasticmq_version' },
            { name: 'node', tag_input: 'node_version' },
          ]

    steps:
      - name: ðŸ”‘ Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        if: ${{ ! env.AWS_ACCESS_KEY_ID }}
        with:
          aws-access-key-id: ${{ secrets.AWS_NONPROD_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_NONPROD_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
        with:
          mask-password: 'true'

      - name: Pull and Push Images to ECR
        run: |
          IMAGE_NAME=${{ matrix.images.name }}
          TAG=${{ inputs[matrix.images.tag_input] }}
          ECR_NAME=${{ matrix.images.name }}
          ECR_BASE="${{ env.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com"

          docker pull $IMAGE_NAME:$TAG
          docker tag $IMAGE_NAME:$TAG $ECR_BASE/$ECR_NAME:$TAG
          docker push $ECR_BASE/$ECR_NAME:$TAG
